### ISSUE TITLE
Should remove dependency of puppet::params and tftp::params

### ISSUE THREAD

**Issue by Yuav** [theforeman/puppet-foreman_proxy#110]
In an environment where you don't want a monolithic foreman deployment (E.G using different modules for puppet and tftp) - it should still be possible to deploy foreman-proxy using Puppet.

**Comment by njm506** [comment]
I'd be wary of keeping any sort of dependency on external modules for what is (at the end of the day) a convenience class; I'm also running in an environment where I don't want to use all of the other Foreman modules, and it seems very irritating to force external dependencies just to get the defaults for a few parameters.  Moving to plugins sounds like it might help, but I still don't want to depend on foreman-puppet just to get the defaults for a few settings.  In my setup, I manually specify these parameters, but I'm currently having to hack around one of the includes by declaring an empty class called puppet::params.

I'd recommend putting sane hard-coded defaults into params, and (if you really want to try to get values from other modules) testing whether a class is included from elsewhere before pulling its defaults in.

**Comment by dc-mattj** [comment]
We also have this issue, I'm trying to move back to using this module after writing our own, but we also have our own puppet module, so including the params class means we either have to fork this module or work out some other hack around as @njm506 has done.

**Comment by mmoll** [comment]
Unsure if that's a real solution, but you could duplicate the needed parameters from `tftp::params` and `puppet:params` into your modules, then the results would be the same...

**Comment by dc-mattj** [comment]
That's a fairly horrible hack. I'm currently forking the module and adding a parameter to include them or not, which defaults to true. Would you accept a PR with that solution ?

**Comment by mmoll** [comment]
Personally I'm leaning towards yes, but would need to see it first and the other maintainers have to agree also... So just open a PR and we'll get things going. :)

**Comment by ekohl** [comment]
In puppet-foreman we also duplicate the SSL dir logic so I think we can do the same here. I think a parameter to conditionally use the duplicated logic or the puppet-puppet logic doesn't make a lot of sense because we're going to need to maintain it anyway. The parameter just complicates it then.

**Comment by dc-mattj** [comment]
I've got to say, that approach is really nasty and breaks all sane Puppet coding style. There's no need for there to be a direct requirement between those modules, and it totally breaks being able to use the foreman-proxy module standalone.

**Comment by ekohl** [comment]
What approach are you referring to? My approach was to add something similar to https://github.com/theforeman/puppet-foreman/blob/837849846c43ca4dcb44f8c61e039c543c576968/manifests/params.pp#L176-L193 to puppet-foreman_proxy and pretty much copy the logic from puppet::params and tftp::params.

**Comment by dc-mattj** [comment]
ah ok, maybe I got the wrong end of the stick. I thought you were saying to duplicate the params files into our modules. Are you saying to remove the dependency completely and just put the logic from the puppet and tftp modules directly into the foreman-proxy module ?

**Comment by dc-mattj** [comment]
Great. Will do that and submit a PR

**Comment by domcleal** [comment]
Merged in #266.
