### ISSUE TITLE
add a parameter to plugins to manage updates/versions

### ISSUE THREAD

**Issue by cristi1979** [theforeman/puppet-foreman_proxy#134]
What do you feel about adding a new parameter to plugins in order to manage updates/versions? The same thing as in init class: $version, but for each plugin? If I send a pull request it will be ok?

**Comment by domcleal** [comment]
Sure, and perhaps have the default value as $::foreman::version.

**Comment by ekohl** [comment]
I think it'd be a good thing as well as long as it defaults to ```installed```.

**Comment by cristi1979** [comment]
I opened PR136 for this, so I will close the issue.
