### ISSUE TITLE
puppet_home points to invalid vardir

### ISSUE THREAD

**Issue by hanej** [theforeman/puppet-foreman_proxy#156]
It looks like the latest version changed $puppet_home from $puppet::params::server_vardir to $puppet::params::vardir.  The problem is $puppet::params::vardir doesn't exist in the theforeman/puppet module.

**Comment by mmoll** [comment]
@hanej this was changed theforeman/puppet-puppet@2c17dfa6c

**Comment by hanej** [comment]
It's broken for everyone who is using the tagged version.  If you point directly to master it works.  In my opinion this is fine to break for the master branch but a tagged release of one module shouldn't depend on the master branch of another.

**Comment by mmoll** [comment]
which version of puppet-foreman_proxy are you using?

**Comment by hanej** [comment]
It auto upgraded to 2.1.0 but we downgraded to 2.0.2 until the puppet-puppet module master branch moves to a tagged release.

**Comment by mmoll** [comment]
@f90b1a5 is not in 2.1.0, which was released at 2014-11-06. To be extra sure, I downloaded theforeman-foreman_proxy-2.1.0.tar.gz from Puppet Forge and found ```$puppet_home = $puppet::params::server_vardir``` in it.

Could you please double-check your setup? Which version of theforeman-puppet are you using?

**Comment by hanej** [comment]
My bad.  Our r10k configuration was configured for master for foreman-proxy.  That's why we had the issue.  Sorry about that.

**Comment by mmoll** [comment]
Thanks for letting us know. :+1:
