### ISSUE TITLE
Parameters to control Puppet manifest caching when using foreman-proxy 1.8

### ISSUE THREAD

**Issue by aamerik** [theforeman/puppet-foreman_proxy#168]
Hello, foreman-proxy 1.8 introduced caching of Puppet manifests on the proxy. I use this module to manage settings.d/puppet.yml and would like to be able to enable manifest caching. Is this a planned feature or is it already in v 2.2.2 (or master)?

Thank you

**Comment by ekohl** [comment]
Personally I was not aware of this feature, but I think it's an easy fix and the module should support it. Patches highly welcome of course :)

**Comment by aamerik** [comment]
:+1:  Thank you!
