### ISSUE TITLE
registered_proxy_url will always default to use port 8443

### ISSUE THREAD

**Issue by cristifalcas** [theforeman/puppet-foreman_proxy#173]
If someone overwrites the variable $ssl_port and not $registered_proxy_url, the variable $registered_proxy_url will always have port 8443 because it will be created before foreman_proxy class is initialized:
- first params class is initialized (due to inheritance) with default values
- in main class any default parameters will take the above default values, even if some of the variables used will be overwritten

In order to fix this, maybe it will be better to not parametrize $registered_proxy_url and construct it in init class instead. I don't see any reason why someone will overwrite registered_proxy_url variable.

The same should be true for: 
- $template_url, which uses default http_port
- $tftp_dirs which uses default tftp_root
- $dns_tsig_principal which uses default dns_realm

**Comment by cristi1979** [comment]
Please let me know if a patch will be accepted that will define registered_proxy_url in init class instead.

**Comment by domcleal** [comment]
> I don't see any reason why someone will overwrite registered_proxy_url variable.

They might want to use a CNAME rather than an FQDN for registration, use an IP or change the protocol.  I think is has to be possible to change this.  It could be constructed later though and have the default as undefined..
