### ISSUE TITLE
dns_key configuration should be optional for dns proxy

### ISSUE THREAD

**Issue by deviantony** [theforeman/puppet-foreman_proxy#180]
In the template file `dns.yml.erb` in any cases the _dns_key_ configuration is set.

For any non production environments, a user may want to use a non secure DNS proxy communication, therefore the dns_key should be removable from the configuration.

**Comment by ekohl** [comment]
I see this has only been fixed in https://github.com/theforeman/puppet-foreman_proxy/commit/753b65c2dad35a5887c46094061703d0a76e3c3c which is not yet in a released version.

**Comment by domcleal** [comment]
It was released in 2.2.3, via 9c648305.

**Comment by ekohl** [comment]
I thought github showed if a certain commit was in a tag, which is why I assumed it wasn't but you're right. I think we can close this then?

**Comment by domcleal** [comment]
Yeah, it's because I cherry picked it, which changes the SHA.  If we'd merged first to the stable branch and merged stable into master then it'd show up.

I think so, let us know if you disagree @deviantony.

**Comment by deviantony** [comment]
What if I want to use the *nsupdate* provider without the *dns_key* parameter?

**Comment by ekohl** [comment]
@deviantony Note ```nsupdate``` vs ```nsupdate_gss```.

**Comment by domcleal** [comment]
Yeah, so what @deviantony's saying is true, that it should probably be possible to not specify dns_key when using nsupdate (so that commit's irrelevant) if bind's configured in an open manner.

**Comment by deviantony** [comment]
@domcleal exactly !

**Comment by ekohl** [comment]
Looking at https://github.com/theforeman/smart-proxy/blob/develop/modules/dns/providers/nsupdate.rb#L59-L63 I'd expect that you can just enter an empty string and the nsupdate provider should ignore it.

**Comment by domcleal** [comment]
An empty string is trueish in Ruby, so it'll append `"-k  "` I suspect.

**Comment by deviantony** [comment]
Tried with an empty string, it is not working. Had to stop the Puppet service and comment the *dns_key* configuration.

**Comment by ekohl** [comment]
IMHO that's also a bug in the smart proxy then. I suppose we could modify our module to skip the value if it's empty.

**Comment by domcleal** [comment]
Indeed, we ought to fix both.

**Comment by ekohl** [comment]
So https://github.com/theforeman/puppet-foreman_proxy/issues/333 should fix it on the puppet side and https://github.com/theforeman/smart-proxy/pull/514 fixes the smart proxy side.
