### ISSUE TITLE
Per-provider DNS configuration files

### ISSUE THREAD

**Issue by domcleal** [theforeman/puppet-foreman_proxy#182]
Smart Proxy 1.10 will ship separate configuration files for DNS providers, instead of one large dns.yml.  The templates in this module will need splitting up.

See https://github.com/theforeman/smart-proxy/tree/d905c67c/config/settings.d for example.

**Comment by ekohl** [comment]
I can't quite figure out we'd do the compatibility. It looks every plugin has its own config "namespace" so we need to figure out which version we're going to deploy for. The ugly solution would be a split_dns_config_files parameter (like we did in puppet-foreman with {report,node}_v{1,2}.rb), but that'd work. It could default to true.

**Comment by domcleal** [comment]
I was thinking that we probably wouldn't bother with compatibility on this change.. but I don't know how many more incompatible changes are coming, and in which releases - I doubt we'd get all of those modules split in time for 1.10, so it might happen again soon.

But yes, I think we'd have to add some new parameters to retain compatibility - either feature based, like whether config files are split or not, or a single version parameter.

**Comment by ekohl** [comment]
Another thing we must handle is ```dns_provider``` changed to ```use_provider```.
