### ISSUE TITLE
plugin templates use wrong variable module_enabled?

### ISSUE THREAD

**Issue by cristifalcas** [theforeman/puppet-foreman_proxy#191]
In almost all plugin templates there is this line:
    :enabled: <%= @module_enabled %>

 Shouldn't that be something like:
    :enabled: <%= scope.lookupvar('::foreman_proxy::plugin::_name_::enabled') %>
?

**Comment by ekohl** [comment]
I think you're missing the actual line.

**Comment by cristifalcas** [comment]
I hit enter by mistake. I updated the question.

**Comment by cristifalcas** [comment]
The chef template is the only one that has:
    :enabled: <%= scope.lookupvar("foreman_proxy::plugin::chef::enabled") %>

**Comment by ekohl** [comment]
No, https://github.com/theforeman/puppet-foreman_proxy/blob/b7eab059e3ea5085cc09a5cfad2db78809bf7a36/manifests/settings_file.pp#L44-L55 takes care of the variable.

**Comment by ekohl** [comment]
Though now I think about it: that should only be for modules. Plugins can use ```@enabled```.

**Comment by cristifalcas** [comment]
Then somethig  is not quite right with rubygem-smart_proxy_abrt. 

When "enabled" is set to https, we get this error:

    [root@puppet falcas]# smart-proxy-abrt-send
    ABRT plugin is disabled - exiting

**Comment by ekohl** [comment]
Can you show the generated config?

**Comment by cristifalcas** [comment]
[root@v-so-repo-01 sdt_user]# cat /etc/foreman-proxy/settings.d/abrt.yml
    ---
    :enabled: https
    # Log file for the forwarding script.
    :abrt_send_log_file: /var/log/foreman-proxy/abrt-send.log
    # Directory where uReports are stored before they are sent
    :spooldir: /var/spool/foreman-proxy-abrt
    # Merge duplicate reports before sending (requires the satyr gem)
    :aggregate_reports: true
    # Period (in seconds) after which collected reports are forwarded. Meaningful
    # only if smart-proxy-abrt-send is run as a daemon (not from cron).
    :send_period: 600
    # FAF server instance the reports will be forwarded to (optional)
    #:server_url:
    # Set to true if FAF server uses self-signed certificate
    #:server_ssl_noverify:
    
    # Following two options enable client authentication to FAF server
    #:server_ssl_cert:
    #:server_ssl_key:

**Comment by ekohl** [comment]
I suspect that ```smart-proxy-abrt-send``` only considers ```enabled``` a boolean. https://github.com/theforeman/smart_proxy_abrt/blob/master/bin/smart-proxy-abrt-send#L26-L30 sure looks that way. The workaround is to set ```listen_on``` to ```both``` for ```foreman_proxy::plugin::abrt```. The proper fix should be done in smart_proxy_abrt.

**Comment by cristifalcas** [comment]
Should I open a issue for that?

**Comment by ekohl** [comment]
Please do.

**Comment by cristifalcas** [comment]
https://github.com/theforeman/smart_proxy_abrt/issues/5

**Comment by mmoll** [comment]
what's the status here?

**Comment by cristifalcas** [comment]
This should be closed, as it seems to be a problem on smart_proxy_abrt

**Comment by mmoll** [comment]
thanks!
