### ISSUE TITLE
Managing wget package causes conflicts with existing packages

### ISSUE THREAD

**Issue by brandonweeks** [theforeman/puppet-foreman_proxy#198]
https://github.com/theforeman/puppet-foreman_proxy/blob/master/manifests/tftp.pp#L32

By managing the wget package unconditionally, foreman_proxy::tftp cannot be used in environments that  already manage the wget package.

**Comment by ekohl** [comment]
Since it uses ensure_packages, you can do the same in your environment or use a dependency. I fully agree it's ugly, but a PR to conditionally manage it would also be accepted.

**Comment by mmoll** [comment]
Some packages were changed to `ensure_packages` to make co-existence with other modules easier, so changing the other module(s) would be preferred, as this also helps these other modules to conflict less. But as said, a PR to set a paramter would also be fine.

**Comment by mmoll** [comment]
what's the status here?

**Comment by mmoll** [comment]
#202 got merged.
