### ISSUE TITLE
Error while running puppet in params.pp on line 253

### ISSUE THREAD

**Issue by nilo72** [theforeman/puppet-foreman_proxy#205]
Could not retrieve catalog from remote server: Error 400 on SERVER: Usage: cache_data(name, initial_data) at /etc/puppet/environments/production/modules/foreman_proxy/manifests/params.pp:253 on node www.example.com

**Comment by ekohl** [comment]
That sounds like you're using a too new puppet-foreman (or too old puppet-foreman_proxy). We recently moved cache_data to https://github.com/puppet-community/puppet-extlib: https://github.com/theforeman/puppet-foreman_proxy/commit/9b9a842b60a5f23cde78caca324f6c25266fedb8 so you need at least version 2.4.0.

**Comment by brandonweeks** [comment]
@ekohl this error actually will happen if you upgrade all the packages and don't restart the puppet server (at least using puppet-server).

**Comment by ekohl** [comment]
@brandonweeks that sounds like a logical explanation as well.

**Comment by mmoll** [comment]
@nilo72 what's the status here?

**Comment by nilo72** [comment]
problem solved. THX
