### ISSUE TITLE
Add parameters to service management

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [theforeman/puppet-foreman_proxy#221]
Currently, parameters to `service` resource are hardcoded. I want to run `foreman-proxy` under `passenger`, so I need service foreman-proxy to be stopped. Solution would be to add `service_ensure` and `service_enable` parameters.

Current workaround is to amend service parameters by:

```
Service <| title == 'foreman-proxy' |> {
        ensure  => stopped,
        enable  => false,
}
```

**Comment by mmoll** [comment]
Pull requests for passenger configurations would be welcome, on the other hand it's very unusual to have -proxy run under passenger as it's very lightweight.

**Comment by mateusz-gozdek-sociomantic** [comment]
I started running `foreman-proxy` under passenger when I experienced some performance issues during class import. But this is [another story](https://tickets.puppetlabs.com/browse/PUP-6000). If I find time to figure out how to write ruby spec files, I will rise an PR.

**Comment by ekohl** [comment]
@mateusz-gozdek-sociomantic is this still an issue you'd like to get solved? Are you still running the proxy under passenger?

**Comment by mateusz-gozdek-sociomantic** [comment]
No, I'm not using it under passenger anymore. Feel free to close it.

**Comment by ekohl** [comment]
Thanks for confirming it.
