### ISSUE TITLE
no parameter named ssl_ca

### ISSUE THREAD

**Issue by jaxxstorm** [theforeman/puppet-foreman_proxy#236]
Looks like the registration provider was updated to have an ssl_ca parameter that doesn't seem to exist?

I'm using the latest version of the foreman module and foreman_proxy modules:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: no parameter named 'ssl_ca' at /etc/puppetlabs/code/environments/foreman_proxy/vendor/foreman_proxy/manifests/register.pp:5 on Foreman_smartproxy[] at /etc/puppetlabs/code/environments/foreman_proxy/vendor/foreman_proxy/manifests/register.pp:5 on node
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by mmoll** [comment]
@jaxxstorm please see the respective commits:
theforeman/puppet-foreman@51e26e5
theforeman/puppet-foreman_proxy@c8c658e

Which (exact) versions of the modules in question are you using, which provider (default or restv2?) and which parametrization? I did test the changes in question, but only with default settings.

**Comment by domcleal** [comment]
If you have both of those commits, you might need to restart your Puppet master to pick up the change in type - it could be cached.

**Comment by mmoll** [comment]
No reaction, closing.
