### ISSUE TITLE
foreman_proxy registration issue with 2.5.0 and foreman 1.11.1

### ISSUE THREAD

**Issue by mleklund** [theforeman/puppet-foreman_proxy#241]
I don't have much to go on other then log entries that look like this:

`Apr 27 10:32:08 cfg01 puppet-agent[15348]: (/Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[cfg01.phx.dealnews.net]) Could not evaluate: Proxy cfg01.phx.dealnews.net cannot be registered ("\xE2" on US-ASCII): N/A`

**Comment by domcleal** [comment]
Any logs from the server?  Debug logs from the agent?

**Comment by mleklund** [comment]
grrr... I can't make it happen on foreground runs, but happens repeatedly on background runs.  There does not seem to be anything in the foreman server logs.  I will keep digging.

**Comment by domcleal** [comment]
The error message and that fact suggest it might be the agent is running in a non-Unicode locale, which is the default on certain versions of Ruby.  Perhaps it's struggling to read the API metadata or response when that happens.

Commenting the `rescue`/exception handler code in the provider (in the `foreman` module) to get a full message and stack trace, plus debug information from the agent may provide more context.

**Comment by mleklund** [comment]
I wiped out my puppet state directory and the problem went away, so something in the puppet agent state was forcing ASCII instead of utf-8.
