### ISSUE TITLE
You must now specify the backend for smart_proxy_dns_powerdns

### ISSUE THREAD

**Issue by mleklund** [theforeman/puppet-foreman_proxy#242]
from https://github.com/theforeman/smart_proxy_dns_powerdns/blob/master/README.md
> To use MySQL, set the following parameters:
> 
> ```
> :powerdns_backend: 'mysql'
> :powerdns_mysql_hostname: 'localhost'
> :powerdns_mysql_username: 'powerdns'
> :powerdns_mysql_password: ''
> :powerdns_mysql_database: 'powerdns'
> ```

So the template is missing `:powerdns_backend: 'mysql'`.  The powerdns plugin also added multiple backend support which would also need to be addressed at some point.

**Comment by mmoll** [comment]
I guess theforeman/foreman-packaging#1033 needs to get in first.

**Comment by mleklund** [comment]
I believe the packages are out now.  Especially with 1.12 hitting.

**Comment by mmoll** [comment]
RPMs are still not done.

**Comment by ekohl** [comment]
RPMs are now done so I'm going to fix this.
