### ISSUE TITLE
::tftp module is not optional

### ISSUE THREAD

**Issue by pkranenburg** [theforeman/puppet-foreman_proxy#270]
Despite setting parameter 'tftp_manage' to false, the module still insists on including ::tftp::params.
This should not happen and can presumably be fixed easily by these modifications:

In params.pp: don't include ::tftp::params
In tftp:pp: lazily evaluate variable 'tftp_root':
  if ($foreman_proxy::tftp_root == undef) {
    initialize from tftp::params
  } else {
    use main parameter value
  }

**Comment by pkranenburg** [comment]
Ok, this issue appears to have been resolved in the current version on github.

I'll retract this issue (#270) and wait for the release to appear.

**Comment by ekohl** [comment]
@domcleal or @mmoll should we do a release?

**Comment by mmoll** [comment]
maybe after #276 ?
