### ISSUE TITLE
Service[smart_proxy_dynflow_core] doesn't seem to be in the catalog

### ISSUE THREAD

**Issue by pschichtel** [theforeman/puppet-foreman_proxy#286]
Using version 4 of this module on Debian Jessie with Foreman Proxy 1.12, the remote_execution::ssh plugin tries to notify the smart_proxy_dynflow_core service, which is no in the catalog. Looking at the code tells me, that it's only defined on redhat based systems.

**Comment by mmoll** [comment]
@iNecas @stbenjam could you have a look at this? On Debian based (and probably also on Fedora) systems, that service shouldn't exist, AFAICT.

**Comment by ekohl** [comment]
I think https://github.com/theforeman/puppet-foreman_proxy/issues/287 solves this, but the ssh plugin has a similar issue.
