### ISSUE TITLE
ruby-smart-proxy-remote-execution-ssh-core package not found

### ISSUE THREAD

**Issue by pschichtel** [theforeman/puppet-foreman_proxy#287]
Using version 4 of this module on Debian Jessie with Foreman Proxy 1.12, the remote_execution::ssh plugin tries to install the package ```ruby-smart-proxy-remote-execution-ssh-core```, but it is not available in the 1.12 repositories.

**Comment by mmoll** [comment]
@iNecas @stbenjam could you have a look at this? I guess we'll need some compatibility parameter as we normally do want to support 1.12 installs also with version 4.0.x of this module and the new style REX packages won't hit the 1.12 repos.

**Comment by stbenjam** [comment]
Hm, do we really keep compatibility like that? The 1.12 installer branch is pinned to 3.x.  Has this been done for other incompatible changes? I don't remember there being compatability when you redid the DNS providers, for example, but I could be wrong.

**Comment by mmoll** [comment]
I think there was some rule like "current release minus one iteration", @domcleal?
But I wouldn't be against dropping this...

**Comment by pschichtel** [comment]
Well currently the latest stable puppet module is not even incompatible with the latest stable foreman release. In my opinion, a reasonably smooth transition from version to version shoulkd be possible.

**Comment by iNecas** [comment]
Since we are dealing with the core dependnecy in packaging already, I think the safest thing is just to remove that lines that reference the core packages here https://github.com/theforeman/puppet-foreman_proxy/pull/288

**Comment by domcleal** [comment]
> I think there was some rule like "current release minus one iteration", @domcleal?

Usually, yes.

**Comment by ekohl** [comment]
I was under the impression that the packaging change was backported to 1.12.

Personally I think the "current release minus one iteration" is very important because it allows users to run the newest modules even with a slightly older release. This allows early testing of puppet modules which usually results in better releases.

**Comment by mmoll** [comment]
The changes in question never went into 1.12, so nothing to revert there. ;)
As 08f8a55 should be compatible with the packages that are in the 1.12 repos, at least for Debian, after #288 this should be resolved.

**Comment by mmoll** [comment]
Although #286 also looks related.

**Comment by ekohl** [comment]
It appears we didn't catch this because we test our plugins only using RHEL 7 so the Debian code path wasn't covered.
