### ISSUE TITLE
How to set DHCP to true and Manage pools from the DHCP modules ? (cannot redeclare)

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/puppet-foreman_proxy#338]
When I manage my DHCP pools from the foreman-dhcp module and also manage for foreman proxy with dhcp enabled I get:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Class[Dhcp] is already declared; cannot redeclare at /etc/puppetlabs/code/environments/common/foreman_proxy/manifests/proxydhcp.pp:27 at /etc/puppetlabs/code/environments/common/foreman_proxy/manifests/proxydhcp.pp:27:3 on node 

What am I doing wrong here ?

Thanks!

**Comment by domcleal** [comment]
Don't manage it with both. Set `dhcp_managed => false` on foreman_proxy.

**Comment by Yamakasi** [comment]
What is teh preferred way ? There is no good information about it, maybe the docs needs some updating there.
