### ISSUE TITLE
No Puppet user(group) anymore on Puppet 4.9.4 => Puppetlabs Repo RedHat Releases

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/puppet-foreman_proxy#339]
It seems that the user/usergroup is not created anymore when using the PC1 repo from puppetlabs and package 4.9.4

Foreman_proxy gives the following error:

> err	Puppet	Could not set groups on user[foreman-proxy]: Execution of '/usr/sbin/usermod -G puppet foreman-proxy' returned 6: usermod: group 'puppet' does not exist
> err	/Stage[main]/Foreman_proxy::Config/User[foreman-proxy]/groups	change from to puppet failed: Could not set groups on user[foreman-proxy]: Execution of '/usr/sbin/usermod -G puppet foreman-proxy' returned 6: usermod: group 'puppet' does not exist

How can we fix this the best way ?

**Comment by domcleal** [comment]
Ensure `$manage_puppet_group` is enabled (see e12a382e).
