### ISSUE TITLE
foreman.repo needed for puppet-agent-oauth

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/puppet-foreman_proxy#340]
As we need the puppet-agent-oauth package we also need the foreman.repo which is not added by default.

**Comment by domcleal** [comment]
The Foreman repository is enabled by default, as it's also used to install foreman-proxy. What parameters precisely are you passing to the module?

**Comment by Yamakasi** [comment]
I don't see it, this is part of my YAML:


```
>   foreman_proxy:
>     dhcp: true
>     dhcp_gateway: 10.0.0.254
>     dhcp_key_name: omapi_key
>     dhcp_key_secret: ohlala_secret ;)
>     dhcp_managed: true
>     dhcp_nameservers: 10.0.0.241,10.0.0.242
>     dhcp_provider: isc
>     dhcp_pxeserver: 10.0.0.241
>     manage_puppet_group: true
>     tftp: true
>     tftp_managed: true
>     tftp_manage_wget: true
>     trusted_hosts:
>     - host1
>     - host2
>     - host3
> 
```

**Comment by domcleal** [comment]
The repository should be enabled then, otherwise the foreman-proxy would also not install. Per https://github.com/theforeman/puppet-foreman_proxy/blob/master/manifests/install.pp#L4 the foreman::repos class should be present.

**Comment by Yamakasi** [comment]
True but the package is not provided and on some other server where I manually added the foreman repo it's available

foreman_proxy server like YAML above
```
# dnf provides puppet-agent-oauth
Failed to synchronize cache for repo 'ovirt-4.0', disabling.
Last metadata expiration check: 0:06:45 ago on Mon Apr  3 14:41:09 2017.
Error: No Matches found
```

Manually installed foreman proxy server:

```
# dnf provides puppet-agent-oauth
Failed to synchronize cache for repo 'ovirt-4.0', disabling.
Last metadata expiration check: 2:09:53 ago on Mon Apr  3 11:49:45 2017.
puppet-agent-oauth-0.5.1-3.el7.noarch : OAuth Core Ruby implementation for Puppet Agent
Repo        : foreman
```

**Comment by domcleal** [comment]
Show the configured repositories using `dnf repolist -v`.

**Comment by Yamakasi** [comment]
# dnf repolist -v
cachedir: /var/cache/dnf
Loaded plugins: Query, generate_completion_cache, config-manager, download, playground, protected_packages, noroot, needs-restarting, debuginfo-install, builddep, reposync, copr
DNF version: 1.1.10
repo: using cache for: puppetlabs-pc1
not found deltainfo for: Puppet Labs PC1 Repository fedora f24 - x86_64
not found updateinfo for: Puppet Labs PC1 Repository fedora f24 - x86_64
repo: using cache for: foreman_proxy
not found deltainfo for: Foreman stable
not found updateinfo for: Foreman stable
repo: using cache for: updates
repo: using cache for: foreman_proxy-plugins
not found deltainfo for: Foreman plugins stable
not found updateinfo for: Foreman plugins stable
repo: using cache for: fedora
not found deltainfo for: Fedora  -
not found updateinfo for: Fedora  -
Cannot download 'http://resources.ovirt.org/pub/yum-repo/mirrorlist-ovirt-4.0-fc24': Cannot prepare internal mirrorlist: No URLs in mirrorlist.
Failed to synchronize cache for repo 'ovirt-4.0', disabling.
puppetlabs-pc1: using metadata from Mon Mar 27 22:52:32 2017.
foreman_proxy: using metadata from Thu Mar  2 15:13:46 2017.
updates: using metadata from Mon Apr  3 02:58:12 2017.
foreman_proxy-plugins: using metadata from Sun Apr  2 19:05:01 2017.
fedora: using metadata from Tue Jun 14 18:07:53 2016.
Last metadata expiration check: 0:13:18 ago on Mon Apr  3 14:41:09 2017.
Repo-id      : fedora
Repo-name    : Fedora  -
Repo-revision: 1465920474
Repo-updated : Tue Jun 14 18:07:53 2016
Repo-pkgs    : 49,722
Repo-size    : 50 G
Repo-baseurl : http://internal-mirror/fedora/linux//releases/24/Everything/x86_64/os/
Repo-expire  : 1,209,600 second(s) (last: Mon Apr  3 04:45:52 2017)
Repo-filename: /etc/yum.repos.d/fedora.repo

Repo-id      : foreman_proxy
Repo-name    : Foreman stable
Repo-revision: 1488464017
Repo-updated : Thu Mar  2 15:13:46 2017
Repo-pkgs    : 311
Repo-size    : 130 M
Repo-baseurl : http://yum.theforeman.org/releases/latest/f24/x86_64
Repo-expire  : 172,800 second(s) (last: Mon Apr  3 04:50:59 2017)
Repo-filename: /etc/yum.repos.d/foreman_proxy.repo

Repo-id      : foreman_proxy-plugins
Repo-name    : Foreman plugins stable
Repo-revision: 1491152699
Repo-updated : Sun Apr  2 19:05:01 2017
Repo-pkgs    : 275
Repo-size    : 38 M
Repo-baseurl : http://yum.theforeman.org/plugins/latest/f24/x86_64
Repo-expire  : 172,800 second(s) (last: Mon Apr  3 04:50:58 2017)
Repo-filename: /etc/yum.repos.d/foreman_proxy-plugins.repo

Repo-id      : puppetlabs-pc1
Repo-name    : Puppet Labs PC1 Repository fedora f24 - x86_64
Repo-revision: 1490647942
Repo-updated : Mon Mar 27 22:52:32 2017
Repo-pkgs    : 21
Repo-size    : 407 M
Repo-baseurl : http://yum.puppetlabs.com/fedora/f24/PC1/x86_64
Repo-expire  : 172,800 second(s) (last: Mon Apr  3 04:46:30 2017)
Repo-filename: /etc/yum.repos.d/puppetlabs-pc1.repo

Repo-id      : updates
Repo-name    : Fedora  -  - Updates
Repo-revision: 1491174275
Repo-tags    : binary-x86_64
Repo-updated : Mon Apr  3 02:58:12 2017
Repo-pkgs    : 15,312
Repo-size    : 23 G
Repo-baseurl : http://internal-mirror/fedora/linux//updates/24/x86_64/
Repo-expire  : 21,600 second(s) (last: Mon Apr  3 14:41:09 2017)
Repo-filename: /etc/yum.repos.d/fedora-updates.repo

**Comment by domcleal** [comment]
The repo is configured:

> Repo-id : foreman_proxy
> Repo-baseurl : http://yum.theforeman.org/releases/latest/f24/x86_64

however, the Foreman repository for Fedora 24 does not ship `puppet-agent-oauth`, it only supports the Puppet package provided by the Fedora 24 operating system.

File a feature request against Foreman's [packaging project](projects.theforeman.org/projects/rpms/issues/) if you need Puppet PC1 support in Foreman's Fedora 24 repositories.

> Manually installed foreman proxy server:
> puppet-agent-oauth-0.5.1-3.el7.noarch : OAuth Core Ruby implementation for Puppet Agent

You have (erroneously) installed an EL7 package on a Fedora system, or this is an EL7 host and therefore a different OS.

**Comment by Yamakasi** [comment]
This sounds more like a mess to me from the packaging part, so the Foreman Devs never thought about this.

This is what is on the F24 lives which has the package

```
Last metadata expiration check: 0:10:21 ago on Mon Apr  3 14:50:07 2017.
repo id                                                       repo name                                                                          status
epel                                                          Extra Packages for Enterprise Linux 7 - x86_64                                     11,446
*fedora                                                       Fedora 24 - x86_64                                                                 49,722
foreman                                                       Foreman 1.14                                                                          468
foreman-plugins                                               Foreman plugins 1.14                                                                  324
group_freeipa-freeipa-4-4                                     Copr repo for freeipa-4-4 owned by @freeipa                                            89
puppetlabs-pc1                                                Puppet Labs PC1 Repository fedora f23 - x86_64                                         27
*updates                                                      Fedora 24 - x86_64 - Updates   
```
