### ISSUE TITLE
CentOS 7.3 First run errors on foreman-proxy install

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/puppet-foreman_proxy#341]
The first run of a fresh install machine with the foreman_proxy module seems to fail on a CentOS 7.3.1611 install. Second run goes well but fails again on the puppet user. 

Is there some cache issue on the first run, IPv6 needs to be disabled to make it default work on any network ?

> Execution of '/usr/bin/yum -d 0 -e 0 -y install foreman-proxy' returned 1: One of the configured repositories failed (Foreman stable),
> and yum doesn't have enough cached data to continue. At this point the only
> safe thing yum can do is fail. There are a few ways to work "fix" this:
> 
> 1. Contact the upstream for the repository and get them to fix the problem.
> 
> 2. Reconfigure the baseurl/etc. for the repository, to point to a working
> upstream. This is most often useful if you are using a newer
> distribution release than is supported by the repository (and the
> packages for the previous distribution release still work).
> 
> 3. Run the command with the repository temporarily disabled
> yum --disablerepo=foreman_proxy ...
> 
> 4. Disable the repository permanently, so yum won't use it by default. Yum
> will then just ignore the repository until you permanently enable it
> again or use --enablerepo for temporary usage:
> 
> yum-config-manager --disable foreman_proxy
> or
> subscription-manager repos --disable=foreman_proxy
> 
> 5. Configure the failing repository to be skipped, if it is unavailable.
> Note that yum will try to contact the repo. when it runs most commands,
> so will have to try and fail each time (and thus. yum will be be much
> slower). If it is a very temporary problem though, this is often a nice
> compromise:
> 
> yum-config-manager --save --setopt=foreman_proxy.skip_if_unavailable=true
> 
> failure: repodata/repomd.xml from foreman_proxy: [Errno 256] No more mirrors to try.
> http://yum.theforeman.org/releases/latest/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2001:4802:7802:103:be76:4eff:fe20:c55: Network is unreachable"
> http://yum.theforeman.org/releases/latest/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2001:4802:7802:103:be76:4eff:fe20:c55: Network is unreachable"
> http://yum.theforeman.org/releases/latest/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2001:4802:7802:103:be76:4eff:fe20:c55: Network is unreachable"
> http://yum.theforeman.org/releases/latest/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2001:4802:7802:103:be76:4eff:fe20:c55: Network is unreachable"
> http://yum.theforeman.org/releases/latest/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2001:4802:7802:103:be76:4eff:fe20:c55: Network is unreachable"
> http://yum.theforeman.org/releases/latest/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2001:4802:7802:103:be76:4eff:fe20:c55: Network is unreachable"
> http://yum.theforeman.org/releases/latest/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2001:4802:7802:103:be76:4eff:fe20:c55: Network is unreachable"
> http://yum.theforeman.org/releases/latest/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2001:4802:7802:103:be76:4eff:fe20:c55: Network is unreachable"
> http://yum.theforeman.org/releases/latest/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2001:4802:7802:103:be76:4eff:fe20:c55: Network is unreachable"
> http://yum.theforeman.org/releases/latest/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2001:4802:7802:103:be76:4eff:fe20:c55: Network is unreachable"

`

**Comment by stbenjam** [comment]
This isn't a problem with the puppet module, you or yum.theforeman.org had some kind of temporary network issue.

**Comment by Yamakasi** [comment]
OK thanks, I had it for a several of times so that can be the issue. Thanks!
