### ISSUE TITLE
Subnet not found

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/puppet-foreman_proxy#343]
I'm having an issue with the setup using this module for DHCP.

When I add a host I get the message "Subnet not found". As this module doesn't add the subnets to the dhcpd.conf, what should be set then ?

Or do I need some other settings on the subnets in Foreman ?

As this is, in the Foreman docs and this module documentation is unclear, what does dhcp_managed actually do ? It grabs the IP/subnet for the DHCP host from facter but that subnet is only usable for starting dhcpd and some hosts in that same subnet, what about the other subnets you want to have in Foreman ?

If we need dhcp_managed on false and configure it on the ::dhcp module itself is it not better to have a pools class in this module as well ?

Please explain as PXE-boot needs dhcp for the host to provision at least and this module makes it unclear on that part.

**Comment by domcleal** [comment]
Please continue using the mailing list for support, this is an issue tracker.

Cross-posted to https://groups.google.com/forum/#!topic/foreman-users/PRtd80lrDK0

**Comment by Yamakasi** [comment]
I'm no so sure, I think we need subnet management into pools to make this properly work. So this might be a bug/feature request.
