### ISSUE TITLE
Duplicate declaration: File[/etc/sudoers.d]

### ISSUE THREAD

**Issue by beetlebolt** [theforeman/puppet-foreman_proxy#389]
I have a conflict with the saz/sudo module v4.2.0. which is also declaring File[/etc/sudoers.d].
Full error:
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: File[/etc/sudoers.d] is already declared in file /etc/puppetlabs/code/environments/development/modules/sudo/manifests/init.pp:147; cannot redeclare at /etc/puppetlabs/code/environments/development/modules/foreman_proxy/manifests/config.pp:119 at /etc/puppetlabs/code/environments/development/modules/foreman_proxy/manifests/config.pp:119:9 on node *mycomputer*

**Comment by alexjfisher** [comment]
Set `manage_sudoersd => false`.  See https://github.com/theforeman/puppet-foreman_proxy/blob/8f0848d27446bd65a3caa5953e9f7304d3964b70/manifests/init.pp#L63-L64
> Whether to manage File['/etc/sudoers.d'] or not.  When reusing this module, this may be disabled to let a dedicated sudo module manage it instead.

**Comment by ekohl** [comment]
As @alexjfisher said: there's a boolean for this. I submitted a PR to use ensure_resource which should decrease the chance of needing this boolean altogether.
