### ISSUE TITLE
forge-8.0.1 contains modules directory

### ISSUE THREAD

**Issue by tabakhase** [theforeman/puppet-foreman_proxy#454]
https://forge.puppet.com/v3/files/theforeman-foreman_proxy-8.0.1.tar.gz 
contains a modules directory filled with stuff.
`8.0.0` and before are clean

**Comment by ekohl** [comment]
Thanks for reporting this. I think this was a mistake from a local test of mine. I'll release 8.0.2 to clean this up.

**Comment by ekohl** [comment]
Closing so the proper changelog will be generated.

**Comment by ekohl** [comment]
8.0.2 is now on the forge. Thanks for reporting!
