### ISSUE TITLE
Default local dhcp pool is not being applied

### ISSUE THREAD

**Issue by salderma** [theforeman/puppet-foreman_proxy#522]
Hello, I posted to the [community site](https://community.theforeman.org/t/smart-proxy-for-provisioning-deployment-with-puppet/14704) yesterday on this topic.  I am effectively looking to use puppet in a Role/Profile scenario to deploy the smart-proxy and components following the Installer Scenario in the documentation (with exceptions):
```
  --enable-foreman-proxy \
  --foreman-proxy-puppet=true \
  --foreman-proxy-puppetca=false \
  --foreman-proxy-tftp=true \
  --foreman-proxy-dhcp=true \
  --foreman-proxy-dhcp-interface=eth0 \ # this should be the target system's primary interface
  --foreman-proxy-dhcp-gateway=10.0.0.1 \ # this is the gateway for target systems' primary interface
  --foreman-proxy-dhcp-nameservers="10.0.1.2,10.0.1.3" \ # this is the same as the gateway
  --foreman-proxy-foreman-base-url=https://foreman.example.com \
  --foreman-proxy-trusted-hosts=foreman.example.com \
  --foreman-proxy-oauth-consumer-key=<key here> \
  --foreman-proxy-oauth-consumer-secret=<secret here>
```

In running `puppet agent --test --debug` on an agent test system, the `::dhcp::pool` resource that should be defined by this module never appears in the debug output.  In addition, neither does the `concat::fragment` which should contain the dhcp pool configuration text.  The debug output only mentions `/etc/dhcp/`, `/etc/dhcp/dhcpd.conf` and related selinux contexts applied to those files.  The dhcpd service fails to start because no subnet is defined on the primary interface.  The `/etc/dhcp/dhcpd.conf` file has nothing below the statement to include configuration drop-in directory.

Can anyone shed some light on this?  Or even perhaps provide a snippet of example puppet code which would accomplish the Foreman-Installer scenario above?

**Comment by ekohl** [comment]
I've replied to the community post because I think it's slightly more visible. To keep the conversation in one place I'm closing this.
