### ISSUE TITLE
foreman 1.22 / puppet 5 needs puppet_version in puppet.yml

### ISSUE THREAD

**Issue by robertvargason** [theforeman/puppet-foreman_proxy#527]
hi

we are using foreman 1.22 with puppet 5.5.14. when I rolled out the new module version 12.0.0, the module changed /etc/foreman-proxy/settings.d/puppet.yml to no longer contain puppet_version:

> -:puppet_version: 5.5.14

which led to an error when restarting the smart-proxy:

> [E] Disabling all modules in the group ['puppet'] due to a failure in one of them: Parameter ':puppet_version' is expected to have a non-empty value

therefore I think the value for puppet_version still needs to be included in the puppet.yml template.

thanks a lot
robert

**Comment by ekohl** [comment]
Thansk for the early feedback. Normally I'm quite strict at maintaining compatibility with older versions, but looks like this time I only kept the 1.23+ version by mistake. Here is where the regression was introduced:

https://github.com/theforeman/puppet-foreman_proxy/commit/9939f88c829fa05550161168b6213de6c2566aa8#diff-e012f57255741c9a402d5c8f09aff7feL16

**Comment by ekohl** [comment]
@robertvargason could you come up with a patch and verify it works in your environment? I'll happily do a 12.0.1 release after.

**Comment by robertvargason** [comment]
the local fix I had to make to get it up and running again was to re-add the line

> :puppet_version: <%= @puppetversion %>

to the file templates/puppet.yml.erb
(for spec tests spec/classes/foreman_proxy__spec.rb needs ":puppet_version: #{Puppet.version}",)

thanks a lot

**Comment by antaflos** [comment]
@ekohl I have created a PR that fixes this issue.

**Comment by ekohl** [comment]
This has been released in 12.0.1
