### ISSUE TITLE
Should pulp3 naming be pulpcore?

### ISSUE THREAD

**Issue by ehelms** [theforeman/puppet-foreman_proxy#550]
We now have a mixed use of conventions with naming some things `pulp3` and others `pulpcore`. 

 * Should we settle on a single convention?
 * Does any scenario make sense to be Pulp 3?
 * Is this an installer / module only issue or also something the smart proxy plugin should account for?
 
@jlsherrill your thoughts would be appreciated

**Comment by ekohl** [comment]
IMHO the installer should follow the smart proxy plugin. We've kept that convention everywhere and makes it straight forward to know an installer option reflects a plugin option.

**Comment by jlsherrill** [comment]
I think it makes sense to standardize on pulpcore, so my vote would be to standardize on pulpcore parameters, and then at some point, update the smartproxy plugin to use 'pulpcore'.  

I'm happy to take the work on updating the smartproxy plugin (and katello changes) now.
