### ISSUE TITLE
Smart proxy plugin packages not lining up

### ISSUE THREAD

**Issue by jadestorm** [theforeman/puppet-foreman_proxy#561]
This change appears to be breaking Foreman Proxy under RHEL7:
https://github.com/theforeman/puppet-foreman_proxy/commit/32b61e3f6a4ee150d65413c201b5cb902ad7ecd3

What it's failing on is:
```
Error: Execution of '/bin/yum -d 0 -e 0 -y install tfm-rubygem-smart_proxy_dynflow' returned 1: Error: Nothing to do
Error: /Stage[main]/Foreman_proxy::Plugin::Dynflow/Foreman_proxy::Plugin[dynflow]/Package[tfm-rubygem-smart_proxy_dynflow]/ensure: change from 'purged' to 'present' failed: Execution of '/bin/yum -d 0 -e 0 -y install tfm-rubygem-smart_proxy_dynflow' returned 1: Error: Nothing to do
Notice: /Stage[main]/Foreman_proxy::Plugin::Dynflow/Foreman_proxy::Settings_file[dynflow]/File[/etc/foreman-proxy/settings.d/dynflow.yml]: Dependency Package[tfm-rubygem-smart_proxy_dynflow] has failures: true
Warning: /Stage[main]/Foreman_proxy::Plugin::Dynflow/Foreman_proxy::Settings_file[dynflow]/File[/etc/foreman-proxy/settings.d/dynflow.yml]: Skipping because of failed dependencies
Error: Execution of '/bin/yum -d 0 -e 0 -y install tfm-rubygem-smart_proxy_ansible' returned 1: Error: Nothing to do
Error: /Stage[main]/Foreman_proxy::Plugin::Ansible/Foreman_proxy::Plugin[ansible]/Package[tfm-rubygem-smart_proxy_ansible]/ensure: change from 'purged' to 'present' failed: Execution of '/bin/yum -d 0 -e 0 -y install tfm-rubygem-smart_proxy_ansible' returned 1: Error: Nothing to do
```

If I look in the actual repo for 1.24 at https://yum.theforeman.org/plugins/1.24/el7/x86_64/ I can see that the non tfm prefixed names appear to be the correct ones.  I don't see any way to configure which plugin package prefix it uses so I'm going to roll back to the previous version of the module.  Am I missing something though?

**Comment by ehelms** [comment]
The head of the repository has had updates that support Foreman 2.0 which include moving the smart proxy to be packaged within our SCL in order to use newer versions of Ruby. This meant these packages underwent a name change in Foreman 2.0.

**Comment by ekohl** [comment]
Looks like I forgot to update the [README's compatibility matrix](https://github.com/theforeman/puppet-foreman_proxy#compatibility).

**Comment by jadestorm** [comment]
Oh?  First off -- Foreman 2.0?  Nice!  I'm excited.  =)

Second, I'm guessing that it's not going to be a setting adjustment as much as a "keep using the version of the foreman_proxy module that you are using until you get to 2.0"?  (I'm basing that off the compatibility matrix update thing)

**Comment by ekohl** [comment]
For 2.0 we broke with that tradition. In future versions I'll try to keep maintaining that policy.
