### ISSUE TITLE
proxydhcp.pp causing issues during upgrades when VLAN configured on interface

### ISSUE THREAD

**Issue by indygwyn** [theforeman/puppet-foreman_proxy#640]
This code looks pretty old, but I just upgraded a Martello 3.14 to 3.16 and then 3.18 and ran into issues with this code

https://github.com/theforeman/puppet-foreman_proxy/blob/master/manifests/proxydhcp.pp#L6

It looked like it was just using this to determine the IP, network, and net mask and just hardcoding those variables worked for me to get past this issue

**Comment by ekohl** [comment]
Yes, I've been meaning to rewrite it to rely on Facter 3 facts which I think don't need any transformation (dot to underscore etc). I don't have a setup with complex networks but I'd be happy to get it updated. Would you be willing to come up with a patch? I can help guide you if you want.

**Comment by ekohl** [comment]
83f335ffa10f761997753619b37436f6a859896a changed to modern facts which shouldn't have this issue.
